### PR TITLE
update for use with emacs 27

### LINKED ISSUE #15: Error with emacs 27.1
When I try to use faust mode on emacs 27.1, I get:
```
Eager macro-expansion failure: (error "Invalid rx ‘any’ range: ^-+")
rx--string-to-intervals: Invalid rx ‘any’ range: ^-+
```

### PR DESCRIPTION
**Pull request by magnetophon**
fixes https://github.com/rukano/emacs-faust-mode/issues/15

### CODE REVIEW

**Review by agraef — APPROVED** [review]
Yep, I can confirm the bug, and this PR fixes it. Thanks @magnetophon and @nbfalcon for the fix! Thumbs up from me. :+1:

**Comment by agraef** [comment]
BTW @magnetophon, would give Stéphane a heads-up, too, so that he updates the Faust source accordingly? Thanks.

**Comment by rukano** [comment]
I'll then proceed to merge. Thanks for the contirbutions!

**Comment by magnetophon** [comment]
Thanks all.

> BTW @magnetophon, would give Stéphane a heads-up, too, so that he updates the Faust source accordingly? Thanks.

Sure: @sletz 

@agraef  You do know he's on github too, right?
 :grin:

**Comment by magnetophon** [comment]
@rukano Could you please update MELPA as well?

**Comment by sletz** [comment]
What has to be done exactly?

**Comment by magnetophon** [comment]
@sletz IIUC, @agraef would like you to merge this change into https://github.com/grame-cncm/faust/blob/master/syntax-highlighting/faust-mode.el

**Comment by sletz** [comment]
@magnetophon  can you do a PR ? Thanks.

**Comment by magnetophon** [comment]
@sletz Here you go: https://github.com/grame-cncm/faust/pull/504

**Pull request merged**
